# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 440)
        MainWindow.setMinimumSize(QtCore.QSize(800, 440))
        MainWindow.setMaximumSize(QtCore.QSize(800, 440))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 330, 421, 40))
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.PasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordInput.setGeometry(QtCore.QRect(200, 240, 421, 20))
        self.PasswordInput.setObjectName("PasswordInput")
        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(200, 130, 421, 20))
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.PasswordLabel.setGeometry(QtCore.QRect(200, 190, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setTextFormat(QtCore.Qt.PlainText)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.PasswordLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.PasswordLabel_2.setGeometry(QtCore.QRect(200, 80, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PasswordLabel_2.setFont(font)
        self.PasswordLabel_2.setTextFormat(QtCore.Qt.PlainText)
        self.PasswordLabel_2.setObjectName("PasswordLabel_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        ## Input Controls

        def passworrd():
            correct = None
            with open("C:\Database\data.txt", "r") as file:
                for line in file:
                    line = line.split(",")
                    if self.UsernameInput.text() == line[0] and self.PasswordInput.text() == line[1]:
                        correct = True

            if correct:
                os.system("redegsp.py")
            else:
                print("incorrect")

        ## End Of Input Controls


        ## Button Controls

        self.pushButton.clicked.connect(passworrd)

        ## End Of Button Controls


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin Panel"))
        self.pushButton.setText(_translate("MainWindow", "Log In"))
        self.PasswordLabel.setText(_translate("MainWindow", "Password"))
        self.PasswordLabel_2.setText(_translate("MainWindow", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
